<?php
/** @var \Sebwite\ProductDownloads\Block\Product\Downloads $block */ 
/** @var \Magento\Framework\Escaper $escaper */

$downloads = $block->getDownloads();
?>
<?php if (count($downloads) > 0): ?>
    <div class="product-downloads s-wysiwyg">
        <ul>
            <?php foreach ($downloads as $download): ?>
                <li>
                    <a href="<?= $escaper->escapeUrl($block->getDownloadUrl($download)); ?>" target="_blank">
                        <?= /* @noEscape */ $download['download_file']; ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <!-- .product-downloads -->
<?php endif; ?>
